//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archient.DesignPatterns.Gumball.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archient.DesignPatterns.Gumball.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning again doesn&apos;t get you another Gumball.
        /// </summary>
        internal static string Crank_Crank {
            get {
                return ResourceManager.GetString("Crank_Crank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you already turned the Crank.
        /// </summary>
        internal static string Crank_Eject {
            get {
                return ResourceManager.GetString("Crank_Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, we&apos;re already giving you a Gumball.
        /// </summary>
        internal static string Crank_Quarter {
            get {
                return ResourceManager.GetString("Crank_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Gumball is on its way!.
        /// </summary>
        internal static string Quarter_Crank {
            get {
                return ResourceManager.GetString("Quarter_Crank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up your Quarter from the tray.
        /// </summary>
        internal static string Quarter_Eject {
            get {
                return ResourceManager.GetString("Quarter_Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t insert another Quarter.
        /// </summary>
        internal static string Quarter_Quarter {
            get {
                return ResourceManager.GetString("Quarter_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to turn the crank first.
        /// </summary>
        internal static string Quarter_Take {
            get {
                return ResourceManager.GetString("Quarter_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pay first.
        /// </summary>
        internal static string Ready_Crank {
            get {
                return ResourceManager.GetString("Ready_Crank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t inserted a Quarter yet.
        /// </summary>
        internal static string Ready_Eject {
            get {
                return ResourceManager.GetString("Ready_Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the Crank for a Gumball.
        /// </summary>
        internal static string Ready_Quarter {
            get {
                return ResourceManager.GetString("Ready_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter for a Gumball.
        /// </summary>
        internal static string Ready_Start {
            get {
                return ResourceManager.GetString("Ready_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter first, then a Gumball.
        /// </summary>
        internal static string Ready_Take {
            get {
                return ResourceManager.GetString("Ready_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Gumballs.
        /// </summary>
        internal static string SoldOut_Crank {
            get {
                return ResourceManager.GetString("SoldOut_Crank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a Slot machine.
        /// </summary>
        internal static string SoldOut_Eject {
            get {
                return ResourceManager.GetString("SoldOut_Eject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Gumballs, please pick up your Quarter.
        /// </summary>
        internal static string SoldOut_Quarter {
            get {
                return ResourceManager.GetString("SoldOut_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the machine is sold out.
        /// </summary>
        internal static string SoldOut_Start {
            get {
                return ResourceManager.GetString("SoldOut_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t give you what I don&apos;t have.
        /// </summary>
        internal static string SoldOut_Take {
            get {
                return ResourceManager.GetString("SoldOut_Take", resourceCulture);
            }
        }
    }
}
